import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  const session = useSession();
  const router = useRouter();

  useEffect(() => {
    if (session.status === "authenticated") {
      router.push("/game");
    }
  }, [session]);

  return (
    <>
      <Head>
        <title>AmongSUS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img src="/among-us-wallpaper-1.webp" className="h-full object-cover" />
      <button
        className="absolute top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%] rounded-xl bg-white py-10 px-20 text-2xl font-bold text-black shadow-2xl"
        onClick={() => {
          signIn();
        }}
      >
        Login
      </button>
    </>
  );
};

export default Home;

// export getServerSideProps() {}
